# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer_files/MainAppDesign.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LITE(object):
    def setupUi(self, LITE):
        LITE.setObjectName("LITE")
        LITE.resize(525, 764)
        self.centralwidget = QtWidgets.QWidget(LITE)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.formatExample = QtWidgets.QWidget()
        self.formatExample.setObjectName("formatExample")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.formatExample)
        self.verticalLayout.setObjectName("verticalLayout")
        self.PasteButtonLayout = QtWidgets.QHBoxLayout()
        self.PasteButtonLayout.setObjectName("PasteButtonLayout")
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.PasteButtonLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.PasteButtonLayout.addItem(spacerItem1)
        self.pasteButton = QtWidgets.QPushButton(self.formatExample)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pasteButton.setFont(font)
        self.pasteButton.setObjectName("pasteButton")
        self.PasteButtonLayout.addWidget(self.pasteButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.PasteButtonLayout.addItem(spacerItem2)
        self.helpButton = QtWidgets.QPushButton(self.formatExample)
        self.helpButton.setMinimumSize(QtCore.QSize(50, 0))
        self.helpButton.setMaximumSize(QtCore.QSize(60, 16777215))
        self.helpButton.setObjectName("helpButton")
        self.PasteButtonLayout.addWidget(self.helpButton)
        self.verticalLayout.addLayout(self.PasteButtonLayout)
        self.DataSourceLayout = QtWidgets.QHBoxLayout()
        self.DataSourceLayout.setObjectName("DataSourceLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.DataSourceLayout.addItem(spacerItem3)
        self.SelectSourceLabel = QtWidgets.QLabel(self.formatExample)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SelectSourceLabel.setFont(font)
        self.SelectSourceLabel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.SelectSourceLabel.setObjectName("SelectSourceLabel")
        self.DataSourceLayout.addWidget(self.SelectSourceLabel)
        self.dataSourceComboBox = QtWidgets.QComboBox(self.formatExample)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataSourceComboBox.sizePolicy().hasHeightForWidth())
        self.dataSourceComboBox.setSizePolicy(sizePolicy)
        self.dataSourceComboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dataSourceComboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.dataSourceComboBox.setObjectName("dataSourceComboBox")
        self.DataSourceLayout.addWidget(self.dataSourceComboBox)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.DataSourceLayout.addItem(spacerItem4)
        self.AddSourceLabel = QtWidgets.QLabel(self.formatExample)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.AddSourceLabel.setFont(font)
        self.AddSourceLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.AddSourceLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.AddSourceLabel.setObjectName("AddSourceLabel")
        self.DataSourceLayout.addWidget(self.AddSourceLabel)
        self.AddSourceButton = QtWidgets.QToolButton(self.formatExample)
        self.AddSourceButton.setObjectName("AddSourceButton")
        self.DataSourceLayout.addWidget(self.AddSourceButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.DataSourceLayout.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.DataSourceLayout)
        self.PastedTextLayout = QtWidgets.QVBoxLayout()
        self.PastedTextLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.PastedTextLayout.setObjectName("PastedTextLayout")
        self.pastedTextLabel = QtWidgets.QLabel(self.formatExample)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pastedTextLabel.sizePolicy().hasHeightForWidth())
        self.pastedTextLabel.setSizePolicy(sizePolicy)
        self.pastedTextLabel.setMaximumSize(QtCore.QSize(16777215, 10))
        self.pastedTextLabel.setAutoFillBackground(False)
        self.pastedTextLabel.setObjectName("pastedTextLabel")
        self.PastedTextLayout.addWidget(self.pastedTextLabel)
        self.clipboardContentTextEdit = QtWidgets.QTextEdit(self.formatExample)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clipboardContentTextEdit.sizePolicy().hasHeightForWidth())
        self.clipboardContentTextEdit.setSizePolicy(sizePolicy)
        self.clipboardContentTextEdit.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.clipboardContentTextEdit.setObjectName("clipboardContentTextEdit")
        self.PastedTextLayout.addWidget(self.clipboardContentTextEdit)
        self.verticalLayout.addLayout(self.PastedTextLayout)
        self.SelectFormattingLayout = QtWidgets.QHBoxLayout()
        self.SelectFormattingLayout.setObjectName("SelectFormattingLayout")
        self.formatStyleLabel = QtWidgets.QLabel(self.formatExample)
        self.formatStyleLabel.setObjectName("formatStyleLabel")
        self.SelectFormattingLayout.addWidget(self.formatStyleLabel)
        self.formatStyleComboBox = QtWidgets.QComboBox(self.formatExample)
        self.formatStyleComboBox.setEditable(False)
        self.formatStyleComboBox.setCurrentText("")
        self.formatStyleComboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.formatStyleComboBox.setObjectName("formatStyleComboBox")
        self.SelectFormattingLayout.addWidget(self.formatStyleComboBox)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.SelectFormattingLayout.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.SelectFormattingLayout)
        self.OptionsLayout = QtWidgets.QVBoxLayout()
        self.OptionsLayout.setObjectName("OptionsLayout")
        self.LanguageNameLayout = QtWidgets.QHBoxLayout()
        self.LanguageNameLayout.setObjectName("LanguageNameLayout")
        self.noLangNameButton = QtWidgets.QRadioButton(self.formatExample)
        self.noLangNameButton.setChecked(True)
        self.noLangNameButton.setObjectName("noLangNameButton")
        self.LanguageNameLayout.addWidget(self.noLangNameButton)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.LanguageNameLayout.addItem(spacerItem7)
        self.languageNameComboBox = QtWidgets.QComboBox(self.formatExample)
        self.languageNameComboBox.setEditable(True)
        self.languageNameComboBox.setObjectName("languageNameComboBox")
        self.LanguageNameLayout.addWidget(self.languageNameComboBox)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LanguageNameLayout.addItem(spacerItem8)
        self.OptionsLayout.addLayout(self.LanguageNameLayout)
        self.langNameFirstLineButton = QtWidgets.QRadioButton(self.formatExample)
        self.langNameFirstLineButton.setObjectName("langNameFirstLineButton")
        self.OptionsLayout.addWidget(self.langNameFirstLineButton)
        self.langNameOnRightButton = QtWidgets.QRadioButton(self.formatExample)
        self.langNameOnRightButton.setObjectName("langNameOnRightButton")
        self.OptionsLayout.addWidget(self.langNameOnRightButton)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.OptionsLayout.addItem(spacerItem9)
        self.DataSourceReferenceLayout = QtWidgets.QHBoxLayout()
        self.DataSourceReferenceLayout.setObjectName("DataSourceReferenceLayout")
        self.noDataSourceButton = QtWidgets.QRadioButton(self.formatExample)
        self.noDataSourceButton.setChecked(True)
        self.noDataSourceButton.setObjectName("noDataSourceButton")
        self.DataSourceReferenceLayout.addWidget(self.noDataSourceButton)
        spacerItem10 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.DataSourceReferenceLayout.addItem(spacerItem10)
        self.dataSourceNameComboBox = QtWidgets.QComboBox(self.formatExample)
        self.dataSourceNameComboBox.setEditable(True)
        self.dataSourceNameComboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.dataSourceNameComboBox.setMinimumContentsLength(7)
        self.dataSourceNameComboBox.setObjectName("dataSourceNameComboBox")
        self.DataSourceReferenceLayout.addWidget(self.dataSourceNameComboBox)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.DataSourceReferenceLayout.addItem(spacerItem11)
        self.OptionsLayout.addLayout(self.DataSourceReferenceLayout)
        self.dataSourceFirstLineButton = QtWidgets.QRadioButton(self.formatExample)
        self.dataSourceFirstLineButton.setObjectName("dataSourceFirstLineButton")
        self.OptionsLayout.addWidget(self.dataSourceFirstLineButton)
        self.dataSourceOnRightButton = QtWidgets.QRadioButton(self.formatExample)
        self.dataSourceOnRightButton.setObjectName("dataSourceOnRightButton")
        self.OptionsLayout.addWidget(self.dataSourceOnRightButton)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.OptionsLayout.addItem(spacerItem12)
        self.litTranslationBox = QtWidgets.QCheckBox(self.formatExample)
        self.litTranslationBox.setObjectName("litTranslationBox")
        self.OptionsLayout.addWidget(self.litTranslationBox)
        self.includeNotesBox = QtWidgets.QCheckBox(self.formatExample)
        self.includeNotesBox.setObjectName("includeNotesBox")
        self.OptionsLayout.addWidget(self.includeNotesBox)
        self.ungrammaticalBox = QtWidgets.QCheckBox(self.formatExample)
        self.ungrammaticalBox.setObjectName("ungrammaticalBox")
        self.OptionsLayout.addWidget(self.ungrammaticalBox)
        self.TextPreviewLayout = QtWidgets.QVBoxLayout()
        self.TextPreviewLayout.setObjectName("TextPreviewLayout")
        self.OutputPreviewLabel = QtWidgets.QLabel(self.formatExample)
        self.OutputPreviewLabel.setObjectName("OutputPreviewLabel")
        self.TextPreviewLayout.addWidget(self.OutputPreviewLabel)
        self.outputPreviewTextEdit = QtWidgets.QTextEdit(self.formatExample)
        self.outputPreviewTextEdit.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.outputPreviewTextEdit.setObjectName("outputPreviewTextEdit")
        self.TextPreviewLayout.addWidget(self.outputPreviewTextEdit)
        self.OptionsLayout.addLayout(self.TextPreviewLayout)
        self.verticalLayout.addLayout(self.OptionsLayout)
        self.CopyButtonLayout = QtWidgets.QHBoxLayout()
        self.CopyButtonLayout.setObjectName("CopyButtonLayout")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.CopyButtonLayout.addItem(spacerItem13)
        self.copyButton = QtWidgets.QPushButton(self.formatExample)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.copyButton.sizePolicy().hasHeightForWidth())
        self.copyButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.copyButton.setFont(font)
        self.copyButton.setObjectName("copyButton")
        self.CopyButtonLayout.addWidget(self.copyButton)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.CopyButtonLayout.addItem(spacerItem14)
        self.verticalLayout.addLayout(self.CopyButtonLayout)
        self.copyNotificationLayout = QtWidgets.QHBoxLayout()
        self.copyNotificationLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.copyNotificationLayout.setObjectName("copyNotificationLayout")
        spacerItem15 = QtWidgets.QSpacerItem(40, 15, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.copyNotificationLayout.addItem(spacerItem15)
        self.updateTimeLabel = QtWidgets.QLabel(self.formatExample)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateTimeLabel.sizePolicy().hasHeightForWidth())
        self.updateTimeLabel.setSizePolicy(sizePolicy)
        self.updateTimeLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.updateTimeLabel.setMaximumSize(QtCore.QSize(16777215, 15))
        self.updateTimeLabel.setText("")
        self.updateTimeLabel.setObjectName("updateTimeLabel")
        self.copyNotificationLayout.addWidget(self.updateTimeLabel)
        spacerItem16 = QtWidgets.QSpacerItem(40, 15, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.copyNotificationLayout.addItem(spacerItem16)
        self.verticalLayout.addLayout(self.copyNotificationLayout)
        self.tabWidget.addTab(self.formatExample, "")
        self.formatStyle = QtWidgets.QWidget()
        self.formatStyle.setObjectName("formatStyle")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.formatStyle)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.styleNameLayout = QtWidgets.QHBoxLayout()
        self.styleNameLayout.setObjectName("styleNameLayout")
        self.styleNameLabel = QtWidgets.QLabel(self.formatStyle)
        self.styleNameLabel.setObjectName("styleNameLabel")
        self.styleNameLayout.addWidget(self.styleNameLabel, 0, QtCore.Qt.AlignRight)
        self.styleNameComboBox = QtWidgets.QComboBox(self.formatStyle)
        self.styleNameComboBox.setObjectName("styleNameComboBox")
        self.styleNameLayout.addWidget(self.styleNameComboBox, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_2.addLayout(self.styleNameLayout)
        self.bodyLayout = QtWidgets.QFormLayout()
        self.bodyLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.bodyLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bodyLayout.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.bodyLayout.setObjectName("bodyLayout")
        self.lineListWidget = QtWidgets.QListWidget(self.formatStyle)
        self.lineListWidget.setMaximumSize(QtCore.QSize(150, 16777215))
        self.lineListWidget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.lineListWidget.setObjectName("lineListWidget")
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.lineListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.lineListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.lineListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.lineListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.lineListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.lineListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.lineListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.lineListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.lineListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.lineListWidget.addItem(item)
        self.bodyLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lineListWidget)
        self.linePropsLayout = QtWidgets.QVBoxLayout()
        self.linePropsLayout.setContentsMargins(-1, -1, -1, 6)
        self.linePropsLayout.setObjectName("linePropsLayout")
        self.linePropsLabel = QtWidgets.QLabel(self.formatStyle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linePropsLabel.sizePolicy().hasHeightForWidth())
        self.linePropsLabel.setSizePolicy(sizePolicy)
        self.linePropsLabel.setMinimumSize(QtCore.QSize(0, 12))
        self.linePropsLabel.setObjectName("linePropsLabel")
        self.linePropsLayout.addWidget(self.linePropsLabel, 0, QtCore.Qt.AlignHCenter)
        self.linePropsInternalLayout = QtWidgets.QFormLayout()
        self.linePropsInternalLayout.setObjectName("linePropsInternalLayout")
        self.legendLabelLabel = QtWidgets.QLabel(self.formatStyle)
        self.legendLabelLabel.setObjectName("legendLabelLabel")
        self.linePropsInternalLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.legendLabelLabel)
        self.legendLabelLineEdit = QtWidgets.QLineEdit(self.formatStyle)
        self.legendLabelLineEdit.setObjectName("legendLabelLineEdit")
        self.linePropsInternalLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.legendLabelLineEdit)
        self.fontSizeLabel = QtWidgets.QLabel(self.formatStyle)
        self.fontSizeLabel.setObjectName("fontSizeLabel")
        self.linePropsInternalLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.fontSizeLabel)
        self.fontSizeLayout = QtWidgets.QHBoxLayout()
        self.fontSizeLayout.setObjectName("fontSizeLayout")
        self.fontSizeLineEdit = QtWidgets.QLineEdit(self.formatStyle)
        self.fontSizeLineEdit.setObjectName("fontSizeLineEdit")
        self.fontSizeLayout.addWidget(self.fontSizeLineEdit)
        self.fontSizeComboBox = QtWidgets.QComboBox(self.formatStyle)
        self.fontSizeComboBox.setObjectName("fontSizeComboBox")
        self.fontSizeLayout.addWidget(self.fontSizeComboBox)
        self.linePropsInternalLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.fontSizeLayout)
        self.fontStyleLabel = QtWidgets.QLabel(self.formatStyle)
        self.fontStyleLabel.setObjectName("fontStyleLabel")
        self.linePropsInternalLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.fontStyleLabel)
        self.fontStyleLayout = QtWidgets.QHBoxLayout()
        self.fontStyleLayout.setObjectName("fontStyleLayout")
        self.comboBox_4 = QtWidgets.QComboBox(self.formatStyle)
        self.comboBox_4.setObjectName("comboBox_4")
        self.fontStyleLayout.addWidget(self.comboBox_4)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.fontStyleLayout.addItem(spacerItem17)
        self.linePropsInternalLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.fontStyleLayout)
        self.linePropsLayout.addLayout(self.linePropsInternalLayout)
        self.removeSpacesCheckBox = QtWidgets.QCheckBox(self.formatStyle)
        self.removeSpacesCheckBox.setObjectName("removeSpacesCheckBox")
        self.linePropsLayout.addWidget(self.removeSpacesCheckBox)
        self.bodyLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.linePropsLayout)
        self.maxWidthLabel = QtWidgets.QLabel(self.formatStyle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxWidthLabel.sizePolicy().hasHeightForWidth())
        self.maxWidthLabel.setSizePolicy(sizePolicy)
        self.maxWidthLabel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.maxWidthLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.maxWidthLabel.setObjectName("maxWidthLabel")
        self.bodyLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.maxWidthLabel)
        self.maxWidthLayout = QtWidgets.QHBoxLayout()
        self.maxWidthLayout.setObjectName("maxWidthLayout")
        self.maxWidthLineEdit = QtWidgets.QLineEdit(self.formatStyle)
        self.maxWidthLineEdit.setMaximumSize(QtCore.QSize(133, 16777215))
        self.maxWidthLineEdit.setAutoFillBackground(False)
        self.maxWidthLineEdit.setClearButtonEnabled(False)
        self.maxWidthLineEdit.setObjectName("maxWidthLineEdit")
        self.maxWidthLayout.addWidget(self.maxWidthLineEdit)
        self.maxWidthComboBox = QtWidgets.QComboBox(self.formatStyle)
        self.maxWidthComboBox.setObjectName("maxWidthComboBox")
        self.maxWidthLayout.addWidget(self.maxWidthComboBox)
        self.bodyLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.maxWidthLayout)
        self.numberedExampleLabel = QtWidgets.QLabel(self.formatStyle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numberedExampleLabel.sizePolicy().hasHeightForWidth())
        self.numberedExampleLabel.setSizePolicy(sizePolicy)
        self.numberedExampleLabel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.numberedExampleLabel.setObjectName("numberedExampleLabel")
        self.bodyLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.numberedExampleLabel)
        self.firstLineLabel = QtWidgets.QLabel(self.formatStyle)
        self.firstLineLabel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.firstLineLabel.setObjectName("firstLineLabel")
        self.bodyLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.firstLineLabel)
        self.subseqLinesLabel = QtWidgets.QLabel(self.formatStyle)
        self.subseqLinesLabel.setObjectName("subseqLinesLabel")
        self.bodyLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.subseqLinesLabel)
        self.numberedExampleLineEdit = QtWidgets.QLineEdit(self.formatStyle)
        self.numberedExampleLineEdit.setObjectName("numberedExampleLineEdit")
        self.bodyLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.numberedExampleLineEdit)
        self.firstLineLineEdit = QtWidgets.QLineEdit(self.formatStyle)
        self.firstLineLineEdit.setObjectName("firstLineLineEdit")
        self.bodyLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.firstLineLineEdit)
        self.subseqLinesLineEdit = QtWidgets.QLineEdit(self.formatStyle)
        self.subseqLinesLineEdit.setObjectName("subseqLinesLineEdit")
        self.bodyLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.subseqLinesLineEdit)
        self.formatForLabel = QtWidgets.QLabel(self.formatStyle)
        self.formatForLabel.setObjectName("formatForLabel")
        self.bodyLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.formatForLabel)
        self.formatForComboBox = QtWidgets.QComboBox(self.formatStyle)
        self.formatForComboBox.setObjectName("formatForComboBox")
        self.bodyLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.formatForComboBox)
        self.verticalLayout_2.addLayout(self.bodyLayout)
        self.stylePreviewLabel = QtWidgets.QLabel(self.formatStyle)
        self.stylePreviewLabel.setObjectName("stylePreviewLabel")
        self.verticalLayout_2.addWidget(self.stylePreviewLabel)
        self.stylePreviewBrowser = QtWidgets.QTextBrowser(self.formatStyle)
        self.stylePreviewBrowser.setObjectName("stylePreviewBrowser")
        self.verticalLayout_2.addWidget(self.stylePreviewBrowser)
        self.saveButtonsLayout = QtWidgets.QHBoxLayout()
        self.saveButtonsLayout.setObjectName("saveButtonsLayout")
        self.saveButton = QtWidgets.QPushButton(self.formatStyle)
        self.saveButton.setObjectName("saveButton")
        self.saveButtonsLayout.addWidget(self.saveButton, 0, QtCore.Qt.AlignRight)
        self.saveAsButton = QtWidgets.QPushButton(self.formatStyle)
        self.saveAsButton.setObjectName("saveAsButton")
        self.saveButtonsLayout.addWidget(self.saveAsButton, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_2.addLayout(self.saveButtonsLayout)
        self.tabWidget.addTab(self.formatStyle, "")
        self.exampleHistory = QtWidgets.QWidget()
        self.exampleHistory.setObjectName("exampleHistory")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.exampleHistory)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.historyTitleLabel = QtWidgets.QLabel(self.exampleHistory)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.historyTitleLabel.setFont(font)
        self.historyTitleLabel.setObjectName("historyTitleLabel")
        self.horizontalLayout_2.addWidget(self.historyTitleLabel, 0, QtCore.Qt.AlignLeft)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem18)
        self.sortByLabel = QtWidgets.QLabel(self.exampleHistory)
        self.sortByLabel.setObjectName("sortByLabel")
        self.horizontalLayout_2.addWidget(self.sortByLabel)
        self.sortByComboBox = QtWidgets.QComboBox(self.exampleHistory)
        self.sortByComboBox.setObjectName("sortByComboBox")
        self.horizontalLayout_2.addWidget(self.sortByComboBox, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.exampleListView = QtWidgets.QListView(self.exampleHistory)
        self.exampleListView.setObjectName("exampleListView")
        self.verticalLayout_3.addWidget(self.exampleListView)
        self.tabWidget.addTab(self.exampleHistory, "")
        self.preferences = QtWidgets.QWidget()
        self.preferences.setObjectName("preferences")
        self.tabWidget.addTab(self.preferences, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        LITE.setCentralWidget(self.centralwidget)

        self.retranslateUi(LITE)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LITE)

    def retranslateUi(self, LITE):
        _translate = QtCore.QCoreApplication.translate
        LITE.setWindowTitle(_translate("LITE", "Linguistic Interlinear Text Exampler"))
        self.pasteButton.setText(_translate("LITE", "Paste FieldWorks Text Segment from clipboard"))
        self.helpButton.setText(_translate("LITE", "Help"))
        self.SelectSourceLabel.setText(_translate("LITE", "Select FlexText Data Source:"))
        self.AddSourceLabel.setText(_translate("LITE", "Add data source:"))
        self.AddSourceButton.setText(_translate("LITE", "..."))
        self.pastedTextLabel.setText(_translate("LITE", "Pasted Fieldworks Text Segment"))
        self.formatStyleLabel.setText(_translate("LITE", "Select format style: "))
        self.noLangNameButton.setText(_translate("LITE", "Do not include language name"))
        self.langNameFirstLineButton.setText(_translate("LITE", "Include language name as first line"))
        self.langNameOnRightButton.setText(_translate("LITE", "Include language name on right"))
        self.noDataSourceButton.setText(_translate("LITE", "Do not include data source reference"))
        self.dataSourceFirstLineButton.setText(_translate("LITE", "Include data source reference as first line"))
        self.dataSourceOnRightButton.setText(_translate("LITE", "Include data source reference on right"))
        self.litTranslationBox.setText(_translate("LITE", "Include literal translation"))
        self.includeNotesBox.setText(_translate("LITE", "Include Notes"))
        self.ungrammaticalBox.setText(_translate("LITE", "Indicate as ungrammatical"))
        self.OutputPreviewLabel.setText(_translate("LITE", "Output preview:"))
        self.copyButton.setText(_translate("LITE", "    Copy formatted example to clipboard    "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.formatExample), _translate("LITE", "Create formatted example"))
        self.styleNameLabel.setText(_translate("LITE", "LITE style name: "))
        __sortingEnabled = self.lineListWidget.isSortingEnabled()
        self.lineListWidget.setSortingEnabled(False)
        item = self.lineListWidget.item(0)
        item.setText(_translate("LITE", "Word"))
        item = self.lineListWidget.item(1)
        item.setText(_translate("LITE", "Morphemes"))
        item = self.lineListWidget.item(2)
        item.setText(_translate("LITE", "Lex. Entries"))
        item = self.lineListWidget.item(3)
        item.setText(_translate("LITE", "Lex. Gloss"))
        item = self.lineListWidget.item(4)
        item.setText(_translate("LITE", "Lex. Gram. Info."))
        item = self.lineListWidget.item(5)
        item.setText(_translate("LITE", "Word Gloss"))
        item = self.lineListWidget.item(6)
        item.setText(_translate("LITE", "Word Cat."))
        item = self.lineListWidget.item(7)
        item.setText(_translate("LITE", "Free Translation"))
        item = self.lineListWidget.item(8)
        item.setText(_translate("LITE", "Literal Translation"))
        item = self.lineListWidget.item(9)
        item.setText(_translate("LITE", "Note"))
        self.lineListWidget.setSortingEnabled(__sortingEnabled)
        self.linePropsLabel.setText(_translate("LITE", "Edit Line Properties"))
        self.legendLabelLabel.setText(_translate("LITE", "Legend label: "))
        self.fontSizeLabel.setText(_translate("LITE", "Font size: "))
        self.fontStyleLabel.setText(_translate("LITE", "Font style: "))
        self.removeSpacesCheckBox.setText(_translate("LITE", "Remove spaces between morphemes on polymorphemic words"))
        self.maxWidthLabel.setText(_translate("LITE", "Maximum width of example: "))
        self.numberedExampleLabel.setText(_translate("LITE", "Numbered Example stylename: "))
        self.firstLineLabel.setText(_translate("LITE", "First line stylename: "))
        self.subseqLinesLabel.setText(_translate("LITE", "Subsequent lines stylename: "))
        self.formatForLabel.setText(_translate("LITE", "Format for: "))
        self.stylePreviewLabel.setText(_translate("LITE", "Preview:"))
        self.saveButton.setText(_translate("LITE", "Save"))
        self.saveAsButton.setText(_translate("LITE", "Save As ..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.formatStyle), _translate("LITE", "Create format styles"))
        self.historyTitleLabel.setText(_translate("LITE", "Previous Examples: "))
        self.sortByLabel.setText(_translate("LITE", "Sort by: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.exampleHistory), _translate("LITE", "Access past examples"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.preferences), _translate("LITE", "Preferences"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LITE = QtWidgets.QMainWindow()
    ui = Ui_LITE()
    ui.setupUi(LITE)
    LITE.show()
    sys.exit(app.exec_())

