# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainAppDesign.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LITE(object):
    def setupUi(self, LITE):
        LITE.setObjectName("LITE")
        LITE.resize(648, 619)
        self.centralwidget = QtWidgets.QWidget(LITE)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.formatExample = QtWidgets.QWidget()
        self.formatExample.setObjectName("formatExample")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.formatExample)
        self.verticalLayout.setObjectName("verticalLayout")
        self.PasteButtonLayout = QtWidgets.QHBoxLayout()
        self.PasteButtonLayout.setObjectName("PasteButtonLayout")
        spacerItem = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.PasteButtonLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.PasteButtonLayout.addItem(spacerItem1)
        self.pasteTextButton = QtWidgets.QPushButton(self.formatExample)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pasteTextButton.sizePolicy().hasHeightForWidth())
        self.pasteTextButton.setSizePolicy(sizePolicy)
        self.pasteTextButton.setMinimumSize(QtCore.QSize(0, 36))
        self.pasteTextButton.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pasteTextButton.setFont(font)
        self.pasteTextButton.setObjectName("pasteTextButton")
        self.PasteButtonLayout.addWidget(self.pasteTextButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.PasteButtonLayout.addItem(spacerItem2)
        self.helpButton = QtWidgets.QPushButton(self.formatExample)
        self.helpButton.setMaximumSize(QtCore.QSize(60, 16777215))
        self.helpButton.setObjectName("helpButton")
        self.PasteButtonLayout.addWidget(self.helpButton)
        self.verticalLayout.addLayout(self.PasteButtonLayout)
        self.PastedTextLayout = QtWidgets.QVBoxLayout()
        self.PastedTextLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.PastedTextLayout.setObjectName("PastedTextLayout")
        self.pastedTextLabel = QtWidgets.QLabel(self.formatExample)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pastedTextLabel.sizePolicy().hasHeightForWidth())
        self.pastedTextLabel.setSizePolicy(sizePolicy)
        self.pastedTextLabel.setMaximumSize(QtCore.QSize(16777215, 10))
        self.pastedTextLabel.setAutoFillBackground(False)
        self.pastedTextLabel.setObjectName("pastedTextLabel")
        self.PastedTextLayout.addWidget(self.pastedTextLabel)
        self.textEdit = QtWidgets.QTextEdit(self.formatExample)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setObjectName("textEdit")
        self.PastedTextLayout.addWidget(self.textEdit)
        self.verticalLayout.addLayout(self.PastedTextLayout)
        self.SelectFormattingLayout = QtWidgets.QHBoxLayout()
        self.SelectFormattingLayout.setObjectName("SelectFormattingLayout")
        self.formatStyleSelectLabel = QtWidgets.QLabel(self.formatExample)
        self.formatStyleSelectLabel.setObjectName("formatStyleSelectLabel")
        self.SelectFormattingLayout.addWidget(self.formatStyleSelectLabel)
        self.formatStyleComboBox = QtWidgets.QComboBox(self.formatExample)
        self.formatStyleComboBox.setEditable(False)
        self.formatStyleComboBox.setCurrentText("")
        self.formatStyleComboBox.setObjectName("formatStyleComboBox")
        self.SelectFormattingLayout.addWidget(self.formatStyleComboBox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.SelectFormattingLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.SelectFormattingLayout)
        self.OptionsLayout = QtWidgets.QVBoxLayout()
        self.OptionsLayout.setObjectName("OptionsLayout")
        self.LanguageNameLayout = QtWidgets.QHBoxLayout()
        self.LanguageNameLayout.setObjectName("LanguageNameLayout")
        self.noLangNameButton = QtWidgets.QRadioButton(self.formatExample)
        self.noLangNameButton.setObjectName("noLangNameButton")
        self.LanguageNameLayout.addWidget(self.noLangNameButton)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.LanguageNameLayout.addItem(spacerItem4)
        self.comboBox = QtWidgets.QComboBox(self.formatExample)
        self.comboBox.setObjectName("comboBox")
        self.LanguageNameLayout.addWidget(self.comboBox)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.LanguageNameLayout.addItem(spacerItem5)
        self.OptionsLayout.addLayout(self.LanguageNameLayout)
        self.langNameFirstLineButton = QtWidgets.QRadioButton(self.formatExample)
        self.langNameFirstLineButton.setObjectName("langNameFirstLineButton")
        self.OptionsLayout.addWidget(self.langNameFirstLineButton)
        self.langNameOnRightButton = QtWidgets.QRadioButton(self.formatExample)
        self.langNameOnRightButton.setObjectName("langNameOnRightButton")
        self.OptionsLayout.addWidget(self.langNameOnRightButton)
        self.line = QtWidgets.QFrame(self.formatExample)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.OptionsLayout.addWidget(self.line)
        self.DataSourceLayout = QtWidgets.QHBoxLayout()
        self.DataSourceLayout.setObjectName("DataSourceLayout")
        self.dataSourceReferenceBox = QtWidgets.QCheckBox(self.formatExample)
        self.dataSourceReferenceBox.setObjectName("dataSourceReferenceBox")
        self.DataSourceLayout.addWidget(self.dataSourceReferenceBox)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.DataSourceLayout.addItem(spacerItem6)
        self.dataSourceComboBox = QtWidgets.QComboBox(self.formatExample)
        self.dataSourceComboBox.setObjectName("dataSourceComboBox")
        self.DataSourceLayout.addWidget(self.dataSourceComboBox)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.DataSourceLayout.addItem(spacerItem7)
        self.AddSourceLabel = QtWidgets.QLabel(self.formatExample)
        self.AddSourceLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.AddSourceLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.AddSourceLabel.setObjectName("AddSourceLabel")
        self.DataSourceLayout.addWidget(self.AddSourceLabel)
        self.AddSourceButton = QtWidgets.QToolButton(self.formatExample)
        self.AddSourceButton.setObjectName("AddSourceButton")
        self.DataSourceLayout.addWidget(self.AddSourceButton)
        self.OptionsLayout.addLayout(self.DataSourceLayout)
        self.litTranslationBox = QtWidgets.QCheckBox(self.formatExample)
        self.litTranslationBox.setObjectName("litTranslationBox")
        self.OptionsLayout.addWidget(self.litTranslationBox)
        self.ungrammaticalBox = QtWidgets.QCheckBox(self.formatExample)
        self.ungrammaticalBox.setObjectName("ungrammaticalBox")
        self.OptionsLayout.addWidget(self.ungrammaticalBox)
        self.TextPreviewLayout = QtWidgets.QVBoxLayout()
        self.TextPreviewLayout.setObjectName("TextPreviewLayout")
        self.OutputPreviewLabel = QtWidgets.QLabel(self.formatExample)
        self.OutputPreviewLabel.setObjectName("OutputPreviewLabel")
        self.TextPreviewLayout.addWidget(self.OutputPreviewLabel)
        self.OutputPreviewTextEdit = QtWidgets.QTextEdit(self.formatExample)
        self.OutputPreviewTextEdit.setObjectName("OutputPreviewTextEdit")
        self.TextPreviewLayout.addWidget(self.OutputPreviewTextEdit)
        self.OptionsLayout.addLayout(self.TextPreviewLayout)
        self.verticalLayout.addLayout(self.OptionsLayout)
        self.OutputTypeLayout = QtWidgets.QHBoxLayout()
        self.OutputTypeLayout.setObjectName("OutputTypeLayout")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.OutputTypeLayout.addItem(spacerItem8)
        self.OutputSelectionLabel = QtWidgets.QLabel(self.formatExample)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.OutputSelectionLabel.setFont(font)
        self.OutputSelectionLabel.setObjectName("OutputSelectionLabel")
        self.OutputTypeLayout.addWidget(self.OutputSelectionLabel)
        self.comboBox_3 = QtWidgets.QComboBox(self.formatExample)
        self.comboBox_3.setObjectName("comboBox_3")
        self.OutputTypeLayout.addWidget(self.comboBox_3)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.OutputTypeLayout.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.OutputTypeLayout)
        self.CopyButtonLayout = QtWidgets.QHBoxLayout()
        self.CopyButtonLayout.setObjectName("CopyButtonLayout")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.CopyButtonLayout.addItem(spacerItem10)
        self.CopyButton = QtWidgets.QPushButton(self.formatExample)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CopyButton.sizePolicy().hasHeightForWidth())
        self.CopyButton.setSizePolicy(sizePolicy)
        self.CopyButton.setMinimumSize(QtCore.QSize(0, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CopyButton.setFont(font)
        self.CopyButton.setObjectName("CopyButton")
        self.CopyButtonLayout.addWidget(self.CopyButton)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.CopyButtonLayout.addItem(spacerItem11)
        self.verticalLayout.addLayout(self.CopyButtonLayout)
        self.tabWidget.addTab(self.formatExample, "")
        self.formatStyle = QtWidgets.QWidget()
        self.formatStyle.setObjectName("formatStyle")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.formatStyle)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.styleNameLayout = QtWidgets.QHBoxLayout()
        self.styleNameLayout.setObjectName("styleNameLayout")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.styleNameLayout.addItem(spacerItem12)
        self.LITEStyleNameLabel = QtWidgets.QLabel(self.formatStyle)
        self.LITEStyleNameLabel.setObjectName("LITEStyleNameLabel")
        self.styleNameLayout.addWidget(self.LITEStyleNameLabel)
        self.comboBox_2 = QtWidgets.QComboBox(self.formatStyle)
        self.comboBox_2.setObjectName("comboBox_2")
        self.styleNameLayout.addWidget(self.comboBox_2)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.styleNameLayout.addItem(spacerItem13)
        self.verticalLayout_6.addLayout(self.styleNameLayout)
        self.formatStyleBodyLayout = QtWidgets.QHBoxLayout()
        self.formatStyleBodyLayout.setObjectName("formatStyleBodyLayout")
        self.toolBox = QtWidgets.QToolBox(self.formatStyle)
        self.toolBox.setAcceptDrops(True)
        self.toolBox.setObjectName("toolBox")
        self.WordPage = QtWidgets.QWidget()
        self.WordPage.setGeometry(QtCore.QRect(0, 0, 227, 226))
        self.WordPage.setAcceptDrops(True)
        self.WordPage.setObjectName("WordPage")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.WordPage)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.legendLabeLayout = QtWidgets.QHBoxLayout()
        self.legendLabeLayout.setObjectName("legendLabeLayout")
        self.legendLabelLabel = QtWidgets.QLabel(self.WordPage)
        self.legendLabelLabel.setObjectName("legendLabelLabel")
        self.legendLabeLayout.addWidget(self.legendLabelLabel)
        self.legendLabelLineEdit = QtWidgets.QLineEdit(self.WordPage)
        self.legendLabelLineEdit.setObjectName("legendLabelLineEdit")
        self.legendLabeLayout.addWidget(self.legendLabelLineEdit)
        self.verticalLayout_7.addLayout(self.legendLabeLayout)
        self.fontSizeLayout = QtWidgets.QHBoxLayout()
        self.fontSizeLayout.setObjectName("fontSizeLayout")
        self.fontSizeLabel = QtWidgets.QLabel(self.WordPage)
        self.fontSizeLabel.setObjectName("fontSizeLabel")
        self.fontSizeLayout.addWidget(self.fontSizeLabel)
        self.fontSizeLineEdit = QtWidgets.QLineEdit(self.WordPage)
        self.fontSizeLineEdit.setObjectName("fontSizeLineEdit")
        self.fontSizeLayout.addWidget(self.fontSizeLineEdit)
        self.fontSizeComboBox = QtWidgets.QComboBox(self.WordPage)
        self.fontSizeComboBox.setObjectName("fontSizeComboBox")
        self.fontSizeLayout.addWidget(self.fontSizeComboBox)
        self.verticalLayout_7.addLayout(self.fontSizeLayout)
        self.fontStyleLayout = QtWidgets.QHBoxLayout()
        self.fontStyleLayout.setObjectName("fontStyleLayout")
        self.fontStyleLabel = QtWidgets.QLabel(self.WordPage)
        self.fontStyleLabel.setObjectName("fontStyleLabel")
        self.fontStyleLayout.addWidget(self.fontStyleLabel)
        self.fontStyleComboBox = QtWidgets.QComboBox(self.WordPage)
        self.fontStyleComboBox.setObjectName("fontStyleComboBox")
        self.fontStyleLayout.addWidget(self.fontStyleComboBox)
        self.verticalLayout_7.addLayout(self.fontStyleLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.addWordButton = QtWidgets.QPushButton(self.WordPage)
        self.addWordButton.setObjectName("addWordButton")
        self.gridLayout_2.addWidget(self.addWordButton, 0, 0, 1, 1)
        self.moveWordUpButton = QtWidgets.QPushButton(self.WordPage)
        self.moveWordUpButton.setObjectName("moveWordUpButton")
        self.gridLayout_2.addWidget(self.moveWordUpButton, 0, 1, 1, 1)
        self.removeWordButton = QtWidgets.QPushButton(self.WordPage)
        self.removeWordButton.setObjectName("removeWordButton")
        self.gridLayout_2.addWidget(self.removeWordButton, 1, 0, 1, 1)
        self.moveWordDownButton = QtWidgets.QPushButton(self.WordPage)
        self.moveWordDownButton.setObjectName("moveWordDownButton")
        self.gridLayout_2.addWidget(self.moveWordDownButton, 1, 1, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_2)
        self.toolBox.addItem(self.WordPage, "")
        self.MorphemesPage = QtWidgets.QWidget()
        self.MorphemesPage.setGeometry(QtCore.QRect(0, 0, 146, 226))
        self.MorphemesPage.setAcceptDrops(True)
        self.MorphemesPage.setObjectName("MorphemesPage")
        self.toolBox.addItem(self.MorphemesPage, "")
        self.LexEntriesPage = QtWidgets.QWidget()
        self.LexEntriesPage.setObjectName("LexEntriesPage")
        self.toolBox.addItem(self.LexEntriesPage, "")
        self.LexGlossPage = QtWidgets.QWidget()
        self.LexGlossPage.setObjectName("LexGlossPage")
        self.toolBox.addItem(self.LexGlossPage, "")
        self.LexGramInfoPage = QtWidgets.QWidget()
        self.LexGramInfoPage.setObjectName("LexGramInfoPage")
        self.toolBox.addItem(self.LexGramInfoPage, "")
        self.WordGlossPage = QtWidgets.QWidget()
        self.WordGlossPage.setObjectName("WordGlossPage")
        self.toolBox.addItem(self.WordGlossPage, "")
        self.WordCatPage = QtWidgets.QWidget()
        self.WordCatPage.setObjectName("WordCatPage")
        self.toolBox.addItem(self.WordCatPage, "")
        self.FreeTranslationPage = QtWidgets.QWidget()
        self.FreeTranslationPage.setObjectName("FreeTranslationPage")
        self.toolBox.addItem(self.FreeTranslationPage, "")
        self.LiteralTranslationPage = QtWidgets.QWidget()
        self.LiteralTranslationPage.setObjectName("LiteralTranslationPage")
        self.toolBox.addItem(self.LiteralTranslationPage, "")
        self.NotePage = QtWidgets.QWidget()
        self.NotePage.setObjectName("NotePage")
        self.toolBox.addItem(self.NotePage, "")
        self.formatStyleBodyLayout.addWidget(self.toolBox)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.ExStyleNameLayout = QtWidgets.QHBoxLayout()
        self.ExStyleNameLayout.setContentsMargins(-1, -1, -1, 6)
        self.ExStyleNameLayout.setObjectName("ExStyleNameLayout")
        self.ExStyleNameLabel = QtWidgets.QLabel(self.formatStyle)
        self.ExStyleNameLabel.setObjectName("ExStyleNameLabel")
        self.ExStyleNameLayout.addWidget(self.ExStyleNameLabel, 0, QtCore.Qt.AlignRight)
        self.lineEdit = QtWidgets.QLineEdit(self.formatStyle)
        self.lineEdit.setObjectName("lineEdit")
        self.ExStyleNameLayout.addWidget(self.lineEdit)
        self.gridLayout.addLayout(self.ExStyleNameLayout, 2, 0, 1, 1)
        self.firstLineStylenameLayout = QtWidgets.QHBoxLayout()
        self.firstLineStylenameLayout.setContentsMargins(-1, -1, -1, 6)
        self.firstLineStylenameLayout.setObjectName("firstLineStylenameLayout")
        self.firstLineStylenameLabel = QtWidgets.QLabel(self.formatStyle)
        self.firstLineStylenameLabel.setObjectName("firstLineStylenameLabel")
        self.firstLineStylenameLayout.addWidget(self.firstLineStylenameLabel, 0, QtCore.Qt.AlignRight)
        self.firstLineStylenameLineEdit = QtWidgets.QLineEdit(self.formatStyle)
        self.firstLineStylenameLineEdit.setObjectName("firstLineStylenameLineEdit")
        self.firstLineStylenameLayout.addWidget(self.firstLineStylenameLineEdit, 0, QtCore.Qt.AlignRight)
        self.gridLayout.addLayout(self.firstLineStylenameLayout, 3, 0, 1, 1)
        self.subLinesStylenameLayout = QtWidgets.QHBoxLayout()
        self.subLinesStylenameLayout.setContentsMargins(-1, -1, -1, 6)
        self.subLinesStylenameLayout.setObjectName("subLinesStylenameLayout")
        self.subLinesStylenameLabel = QtWidgets.QLabel(self.formatStyle)
        self.subLinesStylenameLabel.setObjectName("subLinesStylenameLabel")
        self.subLinesStylenameLayout.addWidget(self.subLinesStylenameLabel, 0, QtCore.Qt.AlignRight)
        self.subLinesStylenameLineEdit = QtWidgets.QLineEdit(self.formatStyle)
        self.subLinesStylenameLineEdit.setObjectName("subLinesStylenameLineEdit")
        self.subLinesStylenameLayout.addWidget(self.subLinesStylenameLineEdit, 0, QtCore.Qt.AlignRight)
        self.gridLayout.addLayout(self.subLinesStylenameLayout, 4, 0, 1, 1)
        self.formatForLayout = QtWidgets.QHBoxLayout()
        self.formatForLayout.setContentsMargins(-1, -1, -1, 6)
        self.formatForLayout.setObjectName("formatForLayout")
        self.FormatForLabel = QtWidgets.QLabel(self.formatStyle)
        self.FormatForLabel.setObjectName("FormatForLabel")
        self.formatForLayout.addWidget(self.FormatForLabel, 0, QtCore.Qt.AlignRight)
        self.formatForComboBox = QtWidgets.QComboBox(self.formatStyle)
        self.formatForComboBox.setObjectName("formatForComboBox")
        self.formatForLayout.addWidget(self.formatForComboBox)
        self.gridLayout.addLayout(self.formatForLayout, 5, 0, 1, 1)
        self.maxWidthLayout = QtWidgets.QHBoxLayout()
        self.maxWidthLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.maxWidthLayout.setContentsMargins(-1, -1, -1, 6)
        self.maxWidthLayout.setObjectName("maxWidthLayout")
        self.maxWidthLabel = QtWidgets.QLabel(self.formatStyle)
        self.maxWidthLabel.setObjectName("maxWidthLabel")
        self.maxWidthLayout.addWidget(self.maxWidthLabel, 0, QtCore.Qt.AlignRight)
        self.widthLineEdit = QtWidgets.QLineEdit(self.formatStyle)
        self.widthLineEdit.setObjectName("widthLineEdit")
        self.maxWidthLayout.addWidget(self.widthLineEdit, 0, QtCore.Qt.AlignRight)
        self.gridLayout.addLayout(self.maxWidthLayout, 1, 0, 1, 1)
        self.unitSelectionComboBox = QtWidgets.QComboBox(self.formatStyle)
        self.unitSelectionComboBox.setObjectName("unitSelectionComboBox")
        self.gridLayout.addWidget(self.unitSelectionComboBox, 1, 1, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem14)
        self.previewLabel = QtWidgets.QLabel(self.formatStyle)
        self.previewLabel.setObjectName("previewLabel")
        self.verticalLayout_9.addWidget(self.previewLabel)
        self.textBrowser = QtWidgets.QTextBrowser(self.formatStyle)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_9.addWidget(self.textBrowser)
        self.formatStyleBodyLayout.addLayout(self.verticalLayout_9)
        self.verticalLayout_6.addLayout(self.formatStyleBodyLayout)
        self.saveFormatStyleButtonsLayout = QtWidgets.QHBoxLayout()
        self.saveFormatStyleButtonsLayout.setObjectName("saveFormatStyleButtonsLayout")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.saveFormatStyleButtonsLayout.addItem(spacerItem15)
        self.SaveFormatStyleButton = QtWidgets.QPushButton(self.formatStyle)
        self.SaveFormatStyleButton.setObjectName("SaveFormatStyleButton")
        self.saveFormatStyleButtonsLayout.addWidget(self.SaveFormatStyleButton, 0, QtCore.Qt.AlignHCenter)
        self.SaveAsFormatStyleButton = QtWidgets.QPushButton(self.formatStyle)
        self.SaveAsFormatStyleButton.setObjectName("SaveAsFormatStyleButton")
        self.saveFormatStyleButtonsLayout.addWidget(self.SaveAsFormatStyleButton, 0, QtCore.Qt.AlignHCenter)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.saveFormatStyleButtonsLayout.addItem(spacerItem16)
        self.verticalLayout_6.addLayout(self.saveFormatStyleButtonsLayout)
        self.tabWidget.addTab(self.formatStyle, "")
        self.outputFormats = QtWidgets.QWidget()
        self.outputFormats.setObjectName("outputFormats")
        self.tabWidget.addTab(self.outputFormats, "")
        self.preferences = QtWidgets.QWidget()
        self.preferences.setObjectName("preferences")
        self.tabWidget.addTab(self.preferences, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        LITE.setCentralWidget(self.centralwidget)

        self.retranslateUi(LITE)
        self.tabWidget.setCurrentIndex(1)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LITE)

    def retranslateUi(self, LITE):
        _translate = QtCore.QCoreApplication.translate
        LITE.setWindowTitle(_translate("LITE", "Linguistic Interlinear Text Exampler"))
        self.pasteTextButton.setText(_translate("LITE", "  Paste FieldWorks Text Segment from clipboard  "))
        self.helpButton.setText(_translate("LITE", "Help"))
        self.pastedTextLabel.setText(_translate("LITE", "Pasted Fieldworks Text Segment"))
        self.formatStyleSelectLabel.setText(_translate("LITE", "Select format style: "))
        self.noLangNameButton.setText(_translate("LITE", "Do not include language name"))
        self.langNameFirstLineButton.setText(_translate("LITE", "Include language name as first line"))
        self.langNameOnRightButton.setText(_translate("LITE", "Include language name on right"))
        self.dataSourceReferenceBox.setText(_translate("LITE", "Include data source reference"))
        self.AddSourceLabel.setText(_translate("LITE", "Add data source:"))
        self.AddSourceButton.setText(_translate("LITE", "..."))
        self.litTranslationBox.setText(_translate("LITE", "Include literal translation"))
        self.ungrammaticalBox.setText(_translate("LITE", "Indicate as ungrammatical"))
        self.OutputPreviewLabel.setText(_translate("LITE", "Output preview:"))
        self.OutputSelectionLabel.setText(_translate("LITE", "Output as: "))
        self.CopyButton.setText(_translate("LITE", "    Copy formatted example to clipboard    "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.formatExample), _translate("LITE", "Create formatted example"))
        self.LITEStyleNameLabel.setText(_translate("LITE", "LITE style name"))
        self.legendLabelLabel.setText(_translate("LITE", "Legend label:"))
        self.fontSizeLabel.setText(_translate("LITE", "Font size: "))
        self.fontStyleLabel.setText(_translate("LITE", "Font style: "))
        self.addWordButton.setText(_translate("LITE", "Add"))
        self.moveWordUpButton.setText(_translate("LITE", "Move Up"))
        self.removeWordButton.setText(_translate("LITE", "Remove"))
        self.moveWordDownButton.setText(_translate("LITE", "Move Down"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.WordPage), _translate("LITE", "Word"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.MorphemesPage), _translate("LITE", "Morphemes"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.LexEntriesPage), _translate("LITE", "Lex. Entries"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.LexGlossPage), _translate("LITE", "Lex. Gloss"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.LexGramInfoPage), _translate("LITE", "Lex. Gram. Info."))
        self.toolBox.setItemText(self.toolBox.indexOf(self.WordGlossPage), _translate("LITE", "Word Gloss"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.WordCatPage), _translate("LITE", "Word Cat."))
        self.toolBox.setItemText(self.toolBox.indexOf(self.FreeTranslationPage), _translate("LITE", "Free Translation"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.LiteralTranslationPage), _translate("LITE", "Literal Translation"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.NotePage), _translate("LITE", "Note"))
        self.ExStyleNameLabel.setText(_translate("LITE", "Numbered Example stylename: "))
        self.firstLineStylenameLabel.setText(_translate("LITE", "First line stylename: "))
        self.subLinesStylenameLabel.setText(_translate("LITE", "Subsequent lines stylename: "))
        self.FormatForLabel.setText(_translate("LITE", "Format for:"))
        self.maxWidthLabel.setText(_translate("LITE", "Maximum width of example: "))
        self.previewLabel.setText(_translate("LITE", "Preview:"))
        self.SaveFormatStyleButton.setText(_translate("LITE", "Save"))
        self.SaveAsFormatStyleButton.setText(_translate("LITE", "Save As ..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.formatStyle), _translate("LITE", "Create format styles"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.outputFormats), _translate("LITE", "Create output formats"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.preferences), _translate("LITE", "Preferences"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LITE = QtWidgets.QMainWindow()
    ui = Ui_LITE()
    ui.setupUi(LITE)
    LITE.show()
    sys.exit(app.exec_())

